### ISSUE TITLE
Topic: Adding new Topic

### ISSUE THREAD

**Issue by mehrun171** [mdazfar2/HelpOps-Hub#1108]
### Describe the types of DevOps topics you'd add in HelpOps-Hub Resource pages

Lets add the Basic Devops Cycle and its explanation along with each tool used in the Devops Cycle to make people understand the basic things

### How many and what types of DevOps tools are you adding?

Devops Cycle
Tools used at Each stage of Cycle with their respective explanation 

### How many years of experience do you have in the DevOps field?

3months

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [ ] I'm DevOps professional
- [X] Soon, I'll complete it and create a Pull Request.
- [X] I'm a beginner in DevOps, but I'll try to contribute the best resources with hands-on experience.

**Comment by mdazfar2** [comment]
As with 3 years of experience in DevOps, it's the first time I've heard about a new tool named `DevOps cycle`. Can you please elaborate on how it works and how we can use it in the DevOps field? I don't know how you created such an attractive documentation about it. I guess you copied and pasted from somewhere else. Sorry, please don't be discouraged. I just need to know how you can provide the best documentation, which really needs to be learned. I hope you understand; it will help me to assign you. That's why I ask.
