### ISSUE TITLE
**Cursor Pointer Missing on Cards in Home Page**

### ISSUE THREAD

**Issue by ansiace** [mdazfar2/HelpOps-Hub#1408]
### Description

The cards on the Home Page do not have the `cursor: pointer` effect when hovered over. This is inconsistent with best UI/UX practices, where interactive elements like cards should provide visual feedback to indicate they are clickable.

#### Expected Behavior:
- When the user hovers over a card on the Home Page, the cursor should change to a pointer to indicate interactivity.

#### Current Behavior:
- The cursor does not change when hovering over the cards, which might confuse users about the interactivity of the cards.

### Screenshots

https://github.com/user-attachments/assets/9de2b3f7-8ed1-47a8-be6f-633c272e6e34

### Any additional information?

I'm a GSSoC'24-Extd contributor and a Hacktoberfest'24 contributor. Given the scope of the changes

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by ansiace** [comment]
hi @mdazfar2 please assign this issue

**Comment by mdazfar2** [comment]
Hey @ansiace, your observation is very good. Let me explain that the cursor pointer appears where something is functional, like when a redirection occurs upon clicking. On our site, this section is for reading purposes only, so we added a hover effect just for aesthetics and nothing else. Hope you understand. You can raise another issue, and I will be happy to assign it to you, but make sure that the issue you raise is valid and genuinely needs to be addressed on our website; otherwise, invalid issues will be closed. 

_Thank you!_

**Comment by mdazfar2** [comment]
Hey @ansiace, your observation is very good. Let me explain that the cursor pointer appears where something is functional, like when a redirection occurs upon clicking. On our site, this section is for reading purposes only, so we added a hover effect just for aesthetics and nothing else. Hope you understand. 

- You can raise another issue, and I will be happy to assign it to you, but make sure that the issue you raise is valid and genuinely needs to be addressed on our website; otherwise, invalid issues will be closed. 

_Thank you!_
