### ISSUE TITLE
[Feat] Addding Gsap Popup animations to navbar and hero section to give website more Engaging UI

### ISSUE THREAD

**Issue by Hamza1821** [mdazfar2/HelpOps-Hub#1416]
### Description

Adding GSAP popup animations to the navbar and hero section to create a more engaging and dynamic UI, enhancing the user experience by bringing fluid, attention-grabbing interactions to the website.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@Hamza1821 please share the demo video of the GSAP popup animation. It would help me assign this issue to you and make it more understandable for me.

**Comment by Hamza1821** [comment]
https://befiteveryday.netlify.app/ please visit this website this is a project i have contributed recently by adding similar gsap animations.

**Comment by mdazfar2** [comment]
Hey @Hamza1821, this is a very good feature, but it does not look good on our website. According to our website's design, a simpler effect and feature will look more attractive. So, as of now, I don’t think this issue is necessary for our website. Please work on any other issue that is needed and raise issues accordingly. ***Thank you!***
