### ISSUE TITLE
[Feat] Integrate Gemini AI Chat Area in the application

### ISSUE THREAD

**Issue by IkkiOcean** [mdazfar2/HelpOps-Hub#1451]
### **Description:**
This feature request is to integrate a Gemini AI-powered chat area into the HelpsOp application. The goal is to provide DevOps engineers with real-time assistance, troubleshooting, and answers to DevOps-specific queries directly within the app.

### **Benefits:**

- **Immediate Assistance**: Offers DevOps users immediate troubleshooting help, guides, and tips directly in the HelpsOp app.
- **Improved User Productivity**: Reduces time spent searching for DevOps information, enabling users to resolve issues faster.
- **Enhanced User Engagement**: Provides an interactive experience that enhances the value and usability of the HelpsOp platform.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@IkkiOcean, can you do one more thing?

We should provide an option somewhere to create a Dockerfile automatically because many new developers don't know how to run Docker or create a Dockerfile.

We can give an option to add a GitHub repo link, and the AI will fetch all the files and folders, then automatically generate the Dockerfile and provide steps to run it.

We will also provide an option to upload files for developers who haven't pushed their code to GitHub but want to create a Dockerfile without pushing their code. In this case, they can upload the files, and the same process will automatically create the Dockerfile.

Let me know if you can do this because it would be a very helpful feature. It is very interesting thing.
