### ISSUE TITLE
BUG: The Webapp fails compataibility in small screen devices 

### ISSUE THREAD

**Issue by codercake** [mdazfar2/HelpOps-Hub#600]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

The web app fails to adapt to small-screen devices, leading to usability issues where elements may be cut off or inaccessible.
The web app should dynamically adjust its layout and functionality to ensure smooth usability on small-screen devices.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by mdazfar2** [comment]
Hey @codercake, we are now going to shift to Next.js. The code has been converted from HTML, CSS to Next.js. After it is deployed, we will let you know about fixing these bugs and will share our new ideas as well according to the requirements.

- join our official [Discord server](https://discord.gg/UWTrRhqywt) so that we can discuss further about it.
- And also follow us on [Linkedin](https://linkedin.com/company/HelpOps-Hub/)
- And please ⭐ our repo
