### ISSUE TITLE
[Feature]: Add the `Particle.js`

### ISSUE THREAD

**Issue by sivaprasath2004** [mdazfar2/HelpOps-Hub#908]
### Describe the feature

- In this `particle.js` more ui better and `user Experience` 
- this is like modern sites .

- please assign me..

### Add ScreenShots

[Screencast from 2024-07-08 07-54-44.webm](https://github.com/mdazfar2/HelpOps-Hub/assets/121082414/c28b32ca-cba4-44e1-970d-caa121ab4036)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by sivaprasath2004** [comment]
Hello @mdazfar2 please assign me..

**Comment by mdazfar2** [comment]
Hi @sivaprasath2004 Yes, this is a very good effect. However, we already used the same effect on our previous website design. When we made a new modification of the website, we removed this `particle.js` because the effect did not look good on the current website.

- Can you please search for a good issue that I'll be happy to assign to you?
