### ISSUE TITLE
[Feature]: Subcription `mail` Announce

### ISSUE THREAD

**Issue by sivaprasath2004** [mdazfar2/HelpOps-Hub#911]
### Describe the feature

- In this project `input` subscription box cannot accessable . 
- And i want to implement to the `mail ` Announce to the user.
- `Thank you for Subscription` in this maill send to the user mail address this is more efficiently.

### Like this 

- It's more efficient user Experience .

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

**Comment by sivaprasath2004** [comment]
@mdazfar2 please assign me..

**Comment by mdazfar2** [comment]
Hey @sivaprasath2004 It is working well. If you subscribe by entering your valid email, you will recieve a welcome email from official `HelpOps-Hub`. Why do you guys raise issues without checking anything?

**Comment by sivaprasath2004** [comment]
@mdazfar2 I will checked i'll waiting for 5 min i'll not received the mail..

**Comment by mdazfar2** [comment]
Hey @sivaprasath2004, can you do one thing for the button below? When the user clicks on this button, a pop-up message should say "Under Maintenance" because we are creating this page for this button. If you can do this, please raise an issue for it. and create PR as soon as possible. I need it

<br>

![image](https://github.com/mdazfar2/HelpOps-Hub/assets/100375390/87b90e98-a3f1-4127-a034-ecfedd9d71ea)
